@hostname=localhost
@port=8080
GET http://{{hostname}}:{{port}}/health

###
POST http://{{hostname}}:{{port}}/token/request-token
Content-Type: application/json

{
  "ProductId":"12345",
  "AppId":"12345",
  "AppSecret":"12345"
}

###
@token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SWQiOiIxMjM0NSIsIkFwcElkIjoiMTIzNDUiLCJleHAiOjE3MDIwNzkwODgsImlzcyI6Imh0dHBzOi8vbWV1c2Vydmlkb3JkZWF1dGVudGljYWNhby5jb20iLCJhdWQiOiJodHRwczovL21pbmhhYXBsaWNhY2FvLmNvbSJ9.lh0uZHhsa8Wve_YNgnFnDilvvkO2ETGphVd2cuAfS8k"
GET http://{{hostname}}:{{port}}/token/anonymous-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SWQiOiIxMjM0NSIsIkFwcElkIjoiMTIzNDUiLCJleHAiOjE3MDIwNzkwODgsImlzcyI6Imh0dHBzOi8vbWV1c2Vydmlkb3JkZWF1dGVudGljYWNhby5jb20iLCJhdWQiOiJodHRwczovL21pbmhhYXBsaWNhY2FvLmNvbSJ9.lh0uZHhsa8Wve_YNgnFnDilvvkO2ETGphVd2cuAfS8k

{
  "ProductId":"123",
  "AppId":"123",
  "AppSecret":"123"
}

