apiVersion: apps/v1
kind: Deployment
metadata:
  name: registerapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registerapi
  template:
    metadata:
      labels:
        app: registerapi
    spec:
      containers:
      - name: registerapi-container
        image: fabiosfernandes/registerapi:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: meu-secret-docker

---

apiVersion: v1
kind: Service
metadata:
  name: registerapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: registerapi
